default_context:
    author_name: "Grant Nestor"
    author_email: "grantnestor@gmail.com"
    mime_type: "application/vnd.vega.v3+json"
    file_extension: "vg"
    mime_short_name: "Vega"
    extension_name: "jupyterlab_vega"
